# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('publication', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('article_date', models.DateField(blank=True, default=datetime.date.today, max_length=500, null=True)),
                ('article_time', models.TimeField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-article_date', '-article_time'],
            },
        ),
    ]
