# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170607_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ['-created_on', '-article_date', '-article_time']},
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
