# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170611_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='media_type',
            field=models.CharField(choices=[('print', 'print'), ('video', 'video'), ('audio', 'audio'), ('interactive', 'interactive')], default='print', max_length=60),
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
